services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: apeaj-web-dev
    volumes:
      - ./app:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    image: nginx:1.26.2
    container_name: apeaj-nginx-dev
    volumes:
      - static_volume:/usr/src/app/static
      - ./nginx/ssl:/etc/ssl
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
